services:
  mongodb:
    image: mongo:8.0
    container_name: yardly-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db

  backend:
    build:
      context: ./backend
    container_name: yardly-backend-dev
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yardly
      - JWT_SECRET=your_jwt_secret_here
      - PORT=3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: yardly-frontend-dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start -- --host 0.0.0.0 --poll 2000
    depends_on:
      - backend

volumes:
  mongo-data-dev:
